config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home', as: 'home'
  get 'static_pages/spaghettistack', as: 'spaghettistack'
  get 'static_pages/binarytree', as: 'binarytree'
  get 'static_pages/graph', as: 'graph'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def spaghettiStack
  end 

  def binaryTree
  end

  def graph
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# for the navigation bar highlighting
	def is_active(action)
		params[:action] == action ? "active" : nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <div class="container">
        <p class="text-muted">Not really copyright B&R 2014</p>
      </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">

            <%= link_to "Home",home_path(), class:"navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="<%=is_active('graph')%>"><%= link_to "Graph", graph_path() %></li>
              <li class="<%=is_active('spaghettistack')%>"><%= link_to "Spaghetti Stack", spaghettistack_path() %></li>
              <li class="<%=is_active('binarytree')%>"><%= link_to "Tree", binarytree_path() %></li>
             
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | My Favorite Data Structures</title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Static navbar -->
      <%= render 'layouts/navbar' %>
    <%= yield %>
        <%= render 'layouts/footer' %>

  </body>
</html>

app/views/static_pages/binarytree.html.erb
<% provide(:title, "Binary Tree") %>
<h1>Binary Tree</h1>

<div class = "textbox">
	<p>
	  A <span class="italic">Binary tree</span> is a tree-based data structure in which each node has at most two children which are known as the left and right child. 
	</p>
	<p>
		Binary trees are rarely used only for their structure. It is more typical to define values for each node. Binary trees used in this way are used to implement binary search trees and binary heaps, and are used for efficient searching and sorting. The orientation - left or right - of the leaf nodes (nodes with no children) is necessary to maintain a complete tree.
	</p>
</div>
<div class = "picture">
	<%= image_tag("Binary_tree.svg.png", :alt => "Binary Tree") %>
</div>

app/views/static_pages/graph.html.erb
<% provide(:title, "Graph") %>
<h1>Graph</h1>
<div class = "textbox">
	<p>
	  A <span class="italic">graph</span> is a abstract data type that is meant to implement the graph and directed graph concepts from mathematics.

	  A graph data structure is made of a finite set of nodes (or vertices), together with a set of orderd pairs of these nodes. These pairings are called edges or arcs. In math, an edge (x,y) is said to point or go from x to y. These nodes may be a part of the graph structure. 
	</p>
</div>
<div class = "picture">
	<%= image_tag("graph.svg.png", :alt => "Yay Graph!") %>
</div>

app/views/static_pages/home.html.erb
	<h1><b>Home</b></h1>

	<div id = "GraphPanel">

		<p class ="graphpicture">

			<%= image_tag("graph_cartoon.gif", :alt => "Graph me a river.") %>
		</p>

		<p class = "subheader"> 

			<h3> Graph </h3>
		</p>

		<p class = "clear"></p>

		<p class = "info">
			A <%= link_to "Graph", graph_path() %> is not  a normal graph that you would make in Microsoft, it is a series of vertices meant to illustrate a type of relationship. These concepts a taken from mathematics and are seen as well in computer science.
		</p>

	</div>

	<div id = "SpaghettiPanel">

		<p class ="spaghettipicture">

			<%= image_tag("spaghetti.jpg", :alt => "What a impasta...") %>
		</p>

		<p class = "subheader">

			<h3> Spaghetti Stack </h3>
		</p>

		<p class = "clear"></p>

		<p class = "info">
			This  data structure is not good tasting -- named after spaghetti , a <%= link_to "Spaghetti Stack", spaghettistack_path() %> resembles a spaghetti noddle in that it's data structure has one and only one parent pointer.

		</p>

	</div>

	<p class = "clear"></p>


	<div id = "TreePanel">

		<p class ="treepicture">
			<%= image_tag("tree.png", :alt => "Why dont you leaf?") %>
		</p>

		<p class = "subheader">

			<h3> Tree </h3>

		</p>

		<p class = "clear"></p>

		<p class = "info">
			
			"Stay off that Tree Jimmy!"A <%= link_to "Binary Tree", binarytree_path() %> is another data structure. Unlike real trees, these are less dangerous to climb. Their name comes from their tree like structure and that their base nodes are often called leafs.
			
		</p>
	</div>
	<p class = "clear"></p>

app/views/static_pages/spaghettistack.html.erb
<% provide(:title, "Spaghetti Stack") %>

<h1>Spaghetti Stack</h1>

<div class = "textbox">
	<p>
	  A <span class="italic">Spaghetti Stack</span>, also called a cactus stack, saguaro stack, or a in tree, is  an N-ary tree data structure in which child nodes have pointers to the parent nodes (but not vice-versa). When a group of nodes is traveled from a leaf to a root node by tracing the parent pointers, the structure looks like a linked list. It can be compared to a linked list having one and only on parent pointer called a "link", and ignoring that the parent may have more than one child. In this data structure, there are no downward pointers.
	</p>
</div>
<div class = "picture">
	<%= image_tag("Spaghettistack.svg.png", :alt => "Spaghetti Stack") %>
</div>